apiVersion: v1
kind: Secret
metadata:
  name: cavalocal-secrets
  namespace: cavalocal
type: Opaque
stringData:
  POSTGRES_USER: "espe"
  POSTGRES_PASSWORD: "espe123"
  POSTGRES_DB: "cavalocal"
  DATABASE_URL: "postgresql://espe:espe123@postgres:5432/cavalocal?schema=public"
  JWT_SECRET: "cambia-esto-en-produccion"
  RABBITMQ_USER: "audit_user"
  RABBITMQ_PASSWORD: "audit_pass"
  AUDIT_DATABASE_URL: "postgresql://audit:audit@postgres-audit:5432/audit?schema=public"
