server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        sub_filter '</head>' '<script>window.CAVA_API="http://conjunta3p.espe.edu.ec/api";</script></head>';
        sub_filter_once on;
        sub_filter_types text/html;
        try_files $uri $uri/ /index.html;
    }
}
